/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JSlider;

/**
 *
 * @author Abd El Rahman
 */
public class Page2 extends javax.swing.JFrame {
    
       
     private static Page2 instance;
     
     public static Page2 getInstance()
     {
        if(instance != null)
            return instance;
        else
            return instance = new Page2();
    }

    /**
     * Creates new form Page2
     */
    private Page2() {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                setLocation(StartPage.getStartPageGUI().getX() + StartPage.getStartPageGUI().getWidth(), StartPage.getStartPageGUI().getY()+200);
            }
        });
        initComponents();
    }
    
     public void setTemp(String tempreture) {
        this.tempreture.setText(tempreture);
    }

    public void setStatus(String status) {
        this.status.setText(status);
        if (status == "COOLING") 
        {
            this.status.setForeground(Color.BLUE);
        }
        else if (status == "HEATING") 
        {
            this.status.setForeground(Color.RED);
        } 
        else 
        {
            this.status.setForeground(Color.BLUE);
        }
    }
    
    public JSlider getChoclateSlider() {
        return ChocolateSlider;
    }

    public JSlider getCoffeeSlider() {
        return CoffeeSlider;
    }

    public JSlider getLargeSlider() {
        return LargeSlider;
    }

    public JSlider getMediumSlider() {
        return MediumSlider;
    }

    public JSlider getMilkSlider() {
        return MilkSlider;
    }

    public JSlider getSmallSlider() {
        return SmallSlider;
    }

    public JSlider getSugerSlider() {
        return SugerSlider;
    }

    public JSlider getWaterSlider() {
        return WaterSlider;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CoffeeSlider = new javax.swing.JSlider();
        SugerSlider = new javax.swing.JSlider();
        WaterSlider = new javax.swing.JSlider();
        MilkSlider = new javax.swing.JSlider();
        ChocolateSlider = new javax.swing.JSlider();
        SmallSlider = new javax.swing.JSlider();
        MediumSlider = new javax.swing.JSlider();
        LargeSlider = new javax.swing.JSlider();
        tempreture = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee vending machine - status window");

        jPanel1.setBackground(new java.awt.Color(202, 81, 22));
        jPanel1.setName("Status window"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeSlider.setMaximum(20);
        CoffeeSlider.setToolTipText("");
        CoffeeSlider.setValue(0);
        jPanel1.add(CoffeeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, 30));

        SugerSlider.setMaximum(20);
        SugerSlider.setValue(0);
        jPanel1.add(SugerSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 30));

        WaterSlider.setMaximum(200);
        WaterSlider.setValue(0);
        jPanel1.add(WaterSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 320, 30));

        MilkSlider.setMaximum(20);
        MilkSlider.setValue(0);
        jPanel1.add(MilkSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 30));

        ChocolateSlider.setMaximum(20);
        ChocolateSlider.setValue(0);
        jPanel1.add(ChocolateSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 120, 30));

        SmallSlider.setMaximum(20);
        SmallSlider.setValue(0);
        jPanel1.add(SmallSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 120, 30));

        MediumSlider.setMaximum(20);
        MediumSlider.setValue(0);
        jPanel1.add(MediumSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 30));

        LargeSlider.setMaximum(20);
        LargeSlider.setValue(0);
        jPanel1.add(LargeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 120, 30));

        tempreture.setEditable(false);
        tempreture.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jPanel1.add(tempreture, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 50));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Large");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 60, 50));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Water Tempreture");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 50));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Small");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 50, 50));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coffee");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 50));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Medium");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 70, 50));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Water");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, 50));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Chocolate");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, 50));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Milk");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 50));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sugar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, 50));

        status.setBackground(new java.awt.Color(0, 0, 0));
        status.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        status.setText("cooling/heating");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider ChocolateSlider;
    private javax.swing.JSlider CoffeeSlider;
    private javax.swing.JSlider LargeSlider;
    private javax.swing.JSlider MediumSlider;
    private javax.swing.JSlider MilkSlider;
    private javax.swing.JSlider SmallSlider;
    private javax.swing.JSlider SugerSlider;
    private javax.swing.JSlider WaterSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel status;
    private javax.swing.JTextField tempreture;
    // End of variables declaration//GEN-END:variables
}
